version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "assignment"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "letmein"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zz-php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/app
    working_dir: /app

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db-data:
  composer-cache:


